# Generated by Django 4.1.3 on 2023-03-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Admin', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='offer',
        ),
    ]
