# Generated by Django 4.1.3 on 2023-03-08 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api_Home', '0002_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartlist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('pincode', models.CharField(max_length=100)),
                ('paymentmethod', models.CharField(choices=[(1, 'Cash On Delivery'), (2, 'Google Pay'), (3, 'Paytm')], max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
