# Generated by Django 4.1.3 on 2023-03-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Home', '0003_alter_cartlist_options_alter_items_options_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_Home.items'),
            preserve_default=False,
        ),
    ]
