# Generated by Django 4.1.3 on 2023-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Home', '0007_remove_checkout_cart_checkout_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='paymentmethod',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
