# Generated by Django 4.1.3 on 2023-03-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Home', '0009_checkout_created_at_items_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='order',
        ),
    ]
