# Generated by Django 4.1.3 on 2023-03-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Home', '0010_remove_items_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
    ]
