# Generated by Django 4.1.3 on 2023-03-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Home', '0011_remove_checkout_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='payment_method',
        ),
    ]
