# Generated by Django 4.1.3 on 2023-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Home', '0012_alter_checkout_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Cash On Delivery'), (2, 'Google Pay'), (3, 'Paytm')], default=2),
            preserve_default=False,
        ),
    ]
